#!/bin/bash

if [ -z "$1" ]; then
	echo "Hello! This is your first runt."
	echo
	echo "Tell me who you are with: runt hello <first name>"

	exit 0
fi

echo "Nice to meet you, $1!"
echo
echo "Now, try: runt unlock"
echo
echo "It won't work yet but trust the process."
