#!/bin/bash

echo "Nicely done."
echo
echo "Runts are just scripts. If one isn't executable, runt will let you know."
echo
echo "Let's see what we're working with here."
echo

found_anything=false

echo -n "Is Python installed? ... "
if command -v python3 &>/dev/null; then
	found_anything=true

	chmod u+x runts/python
	echo "Nice."
else
	echo "Nope."
fi

echo -n "Is Node.js installed? ... "
if command -v node &>/dev/null; then
	found_anything=true

	chmod u+x runts/node
	echo "Ace."
else
	echo "Nope."
fi

echo -n "Is Docker installed? ... "
if command -v docker &>/dev/null; then
	found_anything=true

	chmod u+x runts/docker
	echo "Cool."
else
	echo "Nope."
fi

echo -n "Is Ruby installed? ... "
if command -v ruby &>/dev/null; then
	found_anything=true

	chmod u+x runts/docker
	echo "Cowabunga."
else
	echo "Nope."
fi

chmod u+x runts/finale

echo

if [ "${found_anything}" = true ]; then
	echo "You've got some good stuff on your system and I just unlocked some more runts to show you."
	echo "See what else you can do now by typing: runt"
else
	echo "I've got some more runts to show off but they require those things I just looked for."
	echo "It doesn't look like you've got any of them installed, unfortunately, but I've still unlocked something for you."
	echo "See the new runt available with: runt"
fi
