#!/bin/bash

if [ "${UNLOCK}" == "everything" ]; then
	if [ "$1" == "--pretty=please" ]; then
		echo "My pleasure, and thanks for saying $1!"
		echo

		if command -v docker &>/dev/null; then
			chmod u+x runts/docker
			echo "I see you have Docker installed. Cool."
		fi

		echo "See what else you can do now by typing: runt"
	else
		echo "Can you ask more nicely than that? Maybe by passing --pretty=please as an argument?"
		echo "Try: UNLOCK=everything runt unlock --pretty=please"
	fi
elif [ -n "${EXCLAMATION}" ]; then
	echo "${EXCLAMATION} is right! I'm glad you feel that way!"
	echo
	echo "I've got a few more things to show you but I've intentionally left them unexecutable."
	echo "We can cut to the chase with: UNLOCK=everything runt unlock --pretty=please"
else
	echo "Nicely done."
	echo
	echo "Runts are just scripts. If one isn't executable, runt will let you know."
	echo
	echo "You can also use environment variables with runts."
	echo "Try: EXCLAMATION=Wowzers runt unlock"
fi
